### ISSUE TITLE
⌨ Physical UI

### ISSUE THREAD

**Issue by martinhofigueiredo** [martinhofigueiredo/SE#2]
Problemas:

- [x] Quantos botões? 
- 1 para ligar/ desligar lâmpada A
- 1 para ligar / desligar lâmpada B
- 1 para aumentar a luminosidade da lâmpada 
- 1 para diminuir luminosidade da lâmpada

**Comment by mariana-dias** [comment]
# Compilar para simulador

<img width="599" alt="barra" src="https://github.com/martinhofigueiredo/SE/assets/115190231/49c55160-159e-4992-8fb5-431ebb7a1b22">


1. Compilar o codigo com a extensão `ESP-IDF` - Cilindro 
    ou no terminal com ```idf.py build```

2. Abrir o terminal da extensão 5 icones a frente do cilindro 

    2.1 ``idf.py uf2``Linking o nosso source code com o bootloader para correr no simulador

> __NOTA__: Nos setting da extensão existe uma variavel que é ``idf.postbuild`` e que deve passar a ter a linha de codigo ```idf.py uf2``` para fazer o linking automático a seguir a dar build

> Tb é crucial o ```Full boot``` attribute on the JSON diagram

Ctrl + Shift + P para abrir simulador

**Comment by martinhofigueiredo** [comment]
```mermaid
flowchart TD    
    direction BT
    C[Client] -- GET/slider/value --> Wifi;
    B1((Button 1)) --> PhysIO;
    B2((Button 2)) --> PhysIO;
    B3((Button 3)) --> PhysIO;
    IR_S((IR Sensor)) --> IR
    subgraph uC
        direction LR
        subgraph PhysIO
            direction TB
            P[Polling Inputs]
            eE[END TASK];
        end
        subgraph IR
            direction TB
            R[Continuosly read IR] --> D[Decode Command]    
            eEe[END TASK];
        end
        m[Internal State Object]
        P --use to update --> m;
        D --use to update --> m;
        m --> eE;
        m --> eEe;
        m --argument--> Update
        subgraph Update
            S[Applies the State Outputs]--> Exit

        end
    end
```

**Comment by josepedrocruz** [comment]
This was reduce to a single button on the lcd of the board
