### ISSUE TITLE
🌐 Web UI

### ISSUE THREAD

**Issue by martinhofigueiredo** [martinhofigueiredo/SE#4]
Objetivos:
- percentagem de luminosidade
- slider para controlar
- on/off
- lista de temporizadores para diminuir luminosidade/desligar

https://chat.openai.com/share/bd0d5a84-dcd2-4339-87af-018dcad64029

**Comment by martinhofigueiredo** [comment]
# Approach

This is being done by using URI pattern matching and decoding the `GET` request to decide what the micro-controller should do.

```mermaid

flowchart TB;
    C[Client] -- GET/slider/value --> uC;
    subgraph uC;
    direction TB;
        URI[URI Handler Function] -- should get --> V[Value as String];
        V --using atoi--> a[Value as int8 0-255];
        a --use to update --> m[Internal State Object];
        m --> e[END TASK];
    end;
```

# 📝 To Do

- [x] Figure out how to pass whats left of the URI and parse it into actionable context (@josepedrocruz) 
- [ ] Display Timers to ensures this part of the code still complies with the __Real Time__ part of the project

**Comment by josepedrocruz** [comment]
[commit: 7d2594f] Figured out how to pass all values from html to main.c

**Comment by josepedrocruz** [comment]
[commit: bec9703] Prettier UI, buttons with delay
